defaults:
  - /entrypoints/InferenceEntrypointCfg@_here_
  - /wandb/WandbCfg@wandb_cfg
  - /samplers/AutoRegressiveSamplerCfg@sampler_cfg
  - _self_
seed: 42
wandb_cfg:
  name: ${sampler_cfg.temperature}temp_${sampler_cfg.sample_fn}_${model_afid}
  group: ant_components                                                                                                                                                                          
  project: qfat
  id: 
  notes: 
  mode: online 
device: mps
training_run_id: 
model_afid: 
sampler_cfg:
  context_len: # leave blank to use the model's context length
  temperature: 0.000001
  sample_fn: gmm 
  horizon: 0
env_cfg:
  _target_: qfat.environments.ant.ant_wrapper.AntWrapper
render_mode: # human # rgb_array 
num_episodes: 1000 
max_steps_per_episode: 1200 # if none, while loop till interrupted
callbacks:
  episode_end:
    - _target_: qfat.callbacks.inference_callbacks.RewardLogger
      reward_reduction: sum
    - _target_: qfat.callbacks.inference_callbacks.EnvBehaviourLogger
      min_sequence_length: 1
      max_sequence_length: 5