defaults:
  - /entrypoints/InferenceEntrypointCfg@_here_
  - /wandb/WandbCfg@wandb_cfg
  - /samplers/AutoRegressiveSamplerCfg@sampler_cfg
  - _self_
seed: 42
wandb_cfg:
  name: ${sampler_cfg.temperature}temp_${sampler_cfg.sample_fn}_${model_afid}  
  group: ur3_inference
  project: qfat
  id: 
  notes: 
  mode: online 
device: mps
training_run_id: 
model_afid: 
sampler_cfg:
  context_len: # leave blank to use the model's context length
  temperature: 0.000001
  horizon: 0
  sample_fn: gmm 
env_cfg:
  _target_: qfat.environments.ur3.ur3_wrapper.UR3Wrapper
render_mode: # rgb_array # human
num_episodes: 1000
max_steps_per_episode: 1000
callbacks:
  episode_end:
    - _target_: qfat.callbacks.inference_callbacks.RewardLogger
    - _target_: qfat.callbacks.inference_callbacks.EnvBehaviourLogger
      min_sequence_length: 2
      max_sequence_length: 2