defaults:
  - /entrypoints/TrainingEntrypointCfg@_here_
  - /wandb/WandbCfg@wandb_cfg
  - /datasets/SlicedTrajectoryDatasetCfg@slicer_cfg
  - /models/QFATCfg@model_cfg
  - /optimizers/OptimizerCfg@model_cfg.optimizer_cfg
  - /models/IdentityEncoderCfg@model_cfg.encoder_cfg
  - /models/DecoderBlockCfg@model_cfg.decoder_block_cfg
  - /models/MultiheadAttentionCfg@model_cfg.decoder_block_cfg.mha_cfg
  - /datasets/MultiPathTrajectoryDatasetCfg@training_dataset_cfg
  - /dataloaders/DataLoaderCfg@train_dataloader_cfg
  - _self_
wandb_cfg:
  name: ${model_cfg.n_layer}layers_${slicer_cfg.window}window
  group: multi_route
  project: qfat
  id:
  notes: 
training_dataset_cfg:
  num_samples: 20000
  noise_scale:
    - [0.65, 0.1]  # Upwards path
    - [0.001, 0.001]  # Diagonal path
    - [0.1, 0.65]  # Right path

train_dataloader_cfg:
  shuffle: true
  batch_size: 1024 
  num_workers: 0
  persistent_workers: false
val_dataloader_cfg:
  shuffle: false
  batch_size: 1024
  num_workers: 0
  persistent_workers: false
model_cfg:
  pad_sampling: false 
  full_covariance: false
  n_layer: 6
  embd_dropout: 0.1 
  context_len: 10
  input_dim: 2
  out_dim: 2 # action_dim*(action_horizon + 1)
  mixture_size: 2
  variance_tol: 1e-8 
  optimizer_cfg:
    n_epochs: 20
    use_cosine_schedule: false
    learning_rate: 0.001
  decoder_block_cfg:
    residual_dropout: 0.1
    mha_cfg:
      embed_dim: 120
      num_heads: 6
      dropout: 0.1
  lambda_mixtures: 0
slicer_cfg:
  window: ${model_cfg.context_len}
  action_horizon: 0
callbacks:
  epoch_end:
    - _target_: qfat.callbacks.train_callbacks.ValidationVarianceCallback
      frequency: ${n_save_model}
    - _target_: qfat.callbacks.train_callbacks.RolloutCallback
      env_cfg:
        _target_: qfat.environments.multi_route.env.MultiRouteEnvV1
        random_reset: true
      sampler_cfg:
        _target_: qfat.samplers.sampler.AutoRegressiveSampler
        context_len: # leave blank to use the model's context length
        temperature: 1
        horizon: ${slicer_cfg.action_horizon}
        use_tensors: true
      frequency: ${n_save_model}
      n_rollouts: 100
      max_steps: 50
      log_entropy: true
      filter_tasks_entropy: 
      min_sequence_length: 1
n_save_model: 1 
n_eval: ${n_save_model}
device: "mps"
train_ratio: 1
reset_epoch: false
reset_cfg: false